spring:
  application:
    name : productsapi
  datasource:
    url: jdbc:h2:mem:produtos
    username: sa
    password: 1234
  jpa:
    database-plataform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always